### ISSUE TITLE
could not run the simulation file 

### ISSUE THREAD

**Issue by ask-more-questions** [seidels/tidetree#1]
hi , i have some problem with the package dependency error when trying to run the SimulatedAlignment.java. do you have any advice?
[A5C55447-BEEE-44D3-BFEB-8727A723FFF8.pdf](https://github.com/seidels/tidetree/files/8821908/A5C55447-BEEE-44D3-BFEB-8727A723FFF8.pdf)

**Comment by seidels** [comment]
Hi, I've just added a pre-release of the TiDeTree package, such that you can use the binaries there directly.

Then, to run a simulation as in Fig. 2 do:
java -jar tidetree.v1.0.0-alpha.1.jar -overwrite -seed 1 -D seqLength=10,outputDir="./simulationOutput/" simulateInputTrees.xml

**Comment by ask-more-questions** [comment]
OK! I will try that.
Thank you very much for replying with great patience!
Best regards,
YeQing&nbsp;





发自我的iPhone


------------------ Original ------------------
From: Sophie Seidel ***@***.***&gt;
Date: Thu,Jun 16,2022 7:54 PM
To: seidels/tidetree ***@***.***&gt;
Cc: ask-more-questions ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [seidels/tidetree] could not run the simulation file  (Issue #1)





 
Hi, I've just added a pre-release of the TiDeTree package, such that you can use the binaries there directly.
 
Then, to run a simulation as in Fig. 2 do:
 java -jar tidetree.v1.0.0-alpha.1.jar -overwrite -seed 1 -D seqLength=10,outputDir="./simulationOutput/" simulateInputTrees.xml
