### ISSUE TITLE
Command to run example

### ISSUE THREAD

**Issue by sashitt2** [seidels/tidetree#3]
Hi, could you please provide the command to run tidetree with example.xml?

Regards
Palash

**Comment by seidels** [comment]
Dear Palash (@sashitt2) and @gilichu,
great to hear that you're interested in running TiDeTree! And sorry for the super long delay! Migrating TiDeTree to BEAST 2.7 has taken me longer than expected. I have added the command to run the example XML into the README file. Let me know if anything else is unclear!
